Add jstachio 1.0.0
jvm-repo-rebuild/reproducible-central pull request #114
Opened 2023-05-25 19:51 UTC by agentgt

Please add jstachio 1.0.0

2023-05-25 19:58 UTC, agentgt commented
@hboutemy I wasn't sure if I should move the files from the wip directory to content?

It appears to build fine with a minor hack I had to do with time zone (ant doesn't UTC on updating archives so it had my America/New_York tz).

2023-05-27 06:33 UTC, hboutemy requested changes
requiring exact 17.0.7 JDK release makes it hard to rebuild (I could not on my laptop, it uses 17.0.6)
can this be avoided?

2023-05-27 06:33 UTC, hboutemy commented on wip/jstachio-1.0.0.buildspec
> +newline=lf
need to add `umask=022`
my own laptop has 002 default umask, and this makes a difference in result

2023-05-27 06:33 UTC, hboutemy commented on wip/jstachio-1.0.0.buildspec
> +buildinfo=api/jstachio/target/${artifactId}-${version}.buildinfo
define `buildinfo=target/jstachio-maven-parent-${version}.buildinfo` to get the aggregated full build output for 31 files, not only 1 random module with 3 files

2023-05-27 06:33 UTC, hboutemy commented
nice work: yes, keeping it in `wip/` while we're working on it is perfect

2023-05-30 00:26 UTC, agentgt commented
I’ll have the changes tomorrow. I will switch it to 1.0.1 of jstachio and use all your recommendations.

My rebuild.sh happen to be an accidental similar name.

It executes a Java file as if it were a script to update the POM. This is because I find the release plugin to not meet my needs.

2023-08-12 18:29 UTC, merged

2023-08-12 18:40 UTC, hboutemy commented
sorry for the long delay, I completely forgot to review
merged, and new releases added like a charm (with my usual `bin/add-new-release.sh` script)

well done, thanks