Add com.corgibytes;versions-maven-plugin;2.11.1
jvm-repo-rebuild/reproducible-central pull request #122
Opened 2023-08-14 14:06 UTC by Vel1khan

2023-08-14 14:54 UTC, Vel1khan commented
I just realised that this is a fork of an already documented reproducible package. Should we keep it?

2023-08-15 15:38 UTC, hboutemy commented
good catch
let's keep it, it's not the first time, and the fact that it's a fork does not change anything against the initial objective = prove that it's reproducible

2023-08-15 16:30 UTC, hboutemy requested changes
please also add maven-metadata.xml

2023-08-21 15:05 UTC, Vel1khan commented on content/com/corgibytes/versions-maven-plugin/versions-maven-plugin-2.11.1.buildspec
> +command="mvn clean package -DskipTests -Dmaven.javadoc.skip -Dgpg.skip"
Huh, did not know that. Seems in this case the build profile was in the parent POM. Would you have any idea on whether it's possible to extract the release profiles directly? Are they always listed like this?

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>${maven-release-plugin.version}</version>
          <configuration>
            <!-- do not deploy site but use instructions in README.md -->
            <goals>deploy</goals>
            <arguments>-Pmojo-release</arguments>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <tagNameFormat>@{project.version}</tagNameFormat>
          </configuration>
        </plugin>
        <plugin>
```

2023-08-21 22:35 UTC, hboutemy commented on content/com/corgibytes/versions-maven-plugin/versions-maven-plugin-2.11.1.buildspec
> +command="mvn clean package -DskipTests -Dmaven.javadoc.skip -Dgpg.skip"
usually, release profile is configured in `maven-release-plugin` (it's a best practice, even if not absolutely necessary)

but usually, i's not done as `argument` but as `releaseProfiles` (= the best practice)

2023-08-21 22:35 UTC, hboutemy approved these changes

2023-08-21 22:35 UTC, merged

2023-08-21 22:37 UTC, hboutemy commented
I suppose https://repo.maven.apache.org/maven2/com/corgibytes/mrm/ is also reproducible as a fork of https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/mojo/mrm/README.md

2023-08-22 14:39 UTC, Vel1khan commented
> I suppose https://repo.maven.apache.org/maven2/com/corgibytes/mrm/ is also reproducible as a fork of https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/mojo/mrm/README.md



> I suppose https://repo.maven.apache.org/maven2/com/corgibytes/mrm/ is also reproducible as a fork of https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/codehaus/mojo/mrm/README.md

Yes it is indeed. I will create the buildspec for it.